title = "Todd With a Blog"
languageCode = "en"

theme = "gokarna"

[params]
    description = ""


[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false



[menu]
    [[menu.main]]
        name = "Home"
        pre = "<span data-feather='home'></span>"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Posts"
        pre = "<span data-feather='book'></span>"
        url = "/posts/"
        weight = 2

    [[menu.main]]
        name = "Tags"
        pre = "<span data-feather='tag'></span>"
        url = "/tags/"
        weight = 4

    [[menu.main]]
        identifier = "github"
        pre = "<span data-feather='github'></span>"
        url = "https://github.com/ToddMCr"
        weight = 5